from distutils.core import setup

setup(
    name='pextant',
    packages=['pextant'],
    version='2.0',
    author='Johannes Norheim',
    author_email='norheim@mit.edu',
    url='http://pypi.python.org/pypi/pextant/',
    download_url='https://github.com/norheim/pextant/archive/1.0.tar.gz',
    keywords=['testing', 'logging', 'example'], # arbitrary keywords
    classifiers=[],
    license='The MIT License: http://www.opensource.org/licenses/mit-license.php',
    description='Python version of SEXTANT pathfinding tool',
    long_description=open('README.txt').read(),
    python_requires='>=3.7',
    install_requires=[
        'appdirs>=1.4.3',
        'asn1crypto>=1.3.0',
        'bokeh>=1.4.0',
        'cloudpickle>=1.3.0',
        'cytoolz>=0.10.1',
        'dask>=2.12.0',
        'docker>=4.2.0',
        'docker-pycreds>=0.4.0',
        'ecdsa>=0.13',
        'eventlet>=0.25.1',
        'Flask-SocketIO>=4.2.1',
        'GDAL>=3.0.2',
        'ipywidgets>=7.5.1',
        'jupyter-console>=6.1.0',
        'mkl-service>=2.3.0',
        'olefile>=0.46',
        'pandas>=0.25.3',
        'pathlib2>=2.3.5',
        'pipdeptree>=0.13.2',
        'pybind11>=2.4.3',
        'pycryptodome>=3.9.7',
        'pynmea2>=1.15.0',
        'pyOpenSSL>=19.1.0',
        'pyproj>=2.4.2.post1',
        'PyQt5>=5.12.3',
        'PyQt5-sip>=4.19.18',
        'PyQtWebEngine>=5.12.1',
        'pyserial>=3.4',
        'PySocks>=1.7.1',
        'pytest>=5.3.2',
        'pywinpty>=0.5.7',
        'qtconsole>=4.7.1',
        'scikit-image>=0.15.0',
        'scipy>=1.3.2',
        'Shapely>=1.6.4.post2',
        'wheel>=0.34.2',
        'win-inet-pton>=1.1.0',
        'wincertstore>=0.2',
    ],
)
