'''=======================================
CLIENT/SERVER
======================================='''
START_SERVER = "START_SERVER"
STOP_SERVER = "STOP_SERVER"
CLIENT_CONNECTED = "CLIENT_CONNECTED"

MESSAGE_RECEIVED = "MESSAGE_RECEIVED"
SEND_MESSAGE_REQUESTED = "SEND_MESSAGE_REQUESTED"

'''=======================================
UI
======================================='''
UI_WINDOW_CLOSED = "UI_WINDOW_CLOSED"

'''=======================================
PATH FINDING
======================================='''
# scenario loading
SCENARIO_LOAD_REQUESTED = "SCENARIO_LOAD_REQUESTED"
SCENARIO_LOAD_COMPLETE = "SCENARIO_LOAD_COMPLETE"
SCENARIO_LOAD_ENDPOINTS_REQUESTED = "SCENARIO_LOAD_ENDPOINTS_REQUESTED"
SCENARIO_LOAD_ENDPOINTS_COMPLETE = "SCENARIO_LOAD_ENDPOINTS_COMPLETE"

# model loading
MODEL_LOAD_REQUESTED = "MODEL_LOAD_REQUESTED"
MODEL_LOAD_COMPLETE = "MODEL_LOAD_COMPLETE"
MODEL_UNLOAD_REQUESTED = "MODEL_UNLOAD_REQUESTED"
MODEL_UNLOAD_COMPLETE = "MODEL_UNLOAD_COMPLETE"

# endpoints
START_POINT_SET_REQUESTED = "START_POINT_SET_REQUESTED"
START_POINT_SET_COMPLETE = "START_POINT_SET_COMPLETE"
END_POINT_SET_REQUESTED = "END_POINT_SET_REQUESTED"
END_POINT_SET_COMPLETE = "END_POINT_SET_COMPLETE"

# obstacle setting
RADIAL_OBSTACLE_SET_REQUESTED = "RADIAL_OBSTACLE_SET_REQUESTED"
OBSTACLE_LIST_SET_REQUESTED = "OBSTACLE_LIST_SET_REQUESTED"
OBSTACLE_CHANGE_COMPLETE = "OBSTACLE_CHANGE_COMPLETE"

# data caching
COSTS_CACHING_REQUESTED = "COSTS_CACHING_REQUESTED"
COSTS_CACHING_COMPLETE = "COSTS_CACHING_COMPLETE"
OBSTACLES_CACHING_REQUESTED = "OBSTACLES_CACHING_REQUESTED"
OBSTACLES_CACHING_COMPLETE = "OBSTACLES_CACHING_COMPLETE"
HEURISTICS_CACHING_REQUESTED = "HEURISTICS_CACHING_REQUESTED"
HEURISTICS_CACHING_COMPLETE = "HEURISTICS_CACHING_COMPLETE"

# path finding
PATH_FIND_REQUESTED = "PATH_FIND_REQUESTED"
PATH_FIND_FROM_POSITION_REQUESTED = "PATH_FIND_FROM_POSITION_REQUESTED"
PATH_FIND_COMPLETE = "PATH_FIND_COMPLETE"
