START_SERVER = "START_SERVER"
STOP_SERVER = "STOP_SERVER"
CLIENT_CONNECTED = "CLIENT_CONNECTED"

MESSAGE_RECEIVED = "MESSAGE_RECEIVED"
SEND_MESSAGE = "SEND_MESSAGE"

UI_WINDOW_CLOSED = "UI_WINDOW_CLOSED"

PATH_FOUND = "PATH_FOUND"
COST_CACHING_COMPLETE = "COST_CACHING_COMPLETE"
TERRAIN_MODEL_LOADED = "TERRAIN_MODEL_LOADED"
