START_SERVER = "START_SERVER"
STOP_SERVER = "STOP_SERVER"
CLIENT_CONNECTED = "CLIENT_CONNECTED"

MESSAGE_RECEIVED = "MESSAGE_RECEIVED"
SEND_MESSAGE = "SEND_MESSAGE"

UI_WINDOW_CLOSED = "UI_WINDOW_CLOSED"
